export enum QuestionType {
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  TRUE_FALSE = "TRUE_FALSE",
  SHORT_ANSWER = "SHORT_ANSWER",
  SORTING = "SORTING",
  MATCHING = "MATCHING",
  FILL_IN_THE_BLANK = "FILL_IN_THE_BLANK",
  TWO_OPTIONS = "TWO_OPTIONS",
  OPEN_ENDED = "OPEN_ENDED"
} 